CoronaProject/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from CoronaProject import views

urlpatterns = [
    
    url(r'^', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path(r'users/',include('users.urls')),
    path('homepage/',include('homepage.urls')),

]

users/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'users'

urlpatterns = [
    url(r'^logout/$', views.logout_user, name='logout_user'),
    path('chooseprofile',views.get_chooseprofile, name = 'chooseprofile'),

    #move to register page 
    path('student/signup',views.get_student_signup, name = 'student_signup'),
    path('teacher/signup',views.get_teacher_signup,name = 'teacher_signup'),
    path(r'manager/signup',views.get_manager_signup, name = 'manager_signup'),

    #register for manager,teacher and student
    path(r'manager/signup_success',views.submit_Manager, name = 'submit_Manager'),
    path(r'teacher/signup_success',views.submit_Teacher, name = 'submit_Teacher'),
    path(r'student/signup_success',views.submit_Student, name = 'submit_Student'),
    
    #connect to all the users
    path(r'Home',views.Conect,name = 'Conect'),

    #phone pages in manager teacher and student
    path('Phones/897<int:user_id>654/',views.Phones),
    path('PhonesT/897<int:user_id>654',views.PhonesTeacher,name = 'PhonesT'),
    path('PhoneStu/897<int:user_id>654',views.PhonesStudent, name = 'PhoneStu'),
    path('StuAdministrativePhones/897<int:user_id>654',views.StuAdministrativePhones, name = 'StuAdministrativePhones'),


    #Home page between paths on the site
    path(r'HomePageTeacher/897<int:user_id>654/',views.HomePageBetweenPathTeacher,name = 'HomePageTeacher'),
    path(r'HomePageManager/897<int:user_id>654/',views.HomePageBetweenPathManager,name = 'HomePageManager'),
    path(r'HomePageStudent/897<int:user_id>654/',views.HomePageBetweenPathStudent, name = 'HomePageStudent'),

    #change status in all the users
    path('ChanageStatusStudent/897<int:user_id>654/',views.ChanageStatusStudent , name = 'ChanageStatusStudent'),
    path('ChanageStatusTeacher/897<int:user_id>654/',views.ChanageStatusTeacher , name = 'ChanageStatusTeacher'),
    path('ChanageStatusManager/897<int:user_id>654/',views.ChanageStatusManager , name = 'ChanageStatusManager'),

    #graph of student status in manager
    path('graphStudentStatus/897<int:user_id>654/',views.graphStudentStatus, name = 'graphStudentStatus'),

    #change all the status of students in class to red
    path('changeMyClassToRed/897<int:user_id>654/',views.changeMyClassToRed,name = 'changeMyClassToRed'),

    #send massege to teacher from manager
    path('massegeForTeacher/897<int:user_id>654/',views.massegeForTeacher, name ='massegeForTeacher'), 
    path('submitMassegeForTeacher/897<int:user_id>654/',views.submitMassegeForTeacher,name = 'submitMassegeForTeacher'),
    
    #send massege to student from manager
    path('massegeForStudentManager/897<int:user_id>654/',views.massegeForStudent_Manager,name = 'massegeForStudentManager' ),
    path('submitMassegeForStudent_Manager/897<int:user_id>654/',views.submitMassegeForStudent_Manager , name = 'submitMassegeForStudent_Manager' ),

    #send massege to class from teacher
    path('massegeForStudentTeacher/897<int:user_id>654/',views.massegeForStudent_Teacher,name='massegeForStudentTeacher'),
    path('submitMassegeForStudent_Teacher/897<int:user_id>654/',views.submitMassegeForStudent_Teacher,name= 'submitMassegeForStudent_Teacher'),

    #get massege from manager in teacher
    path('massegesFromManagerInTeacher/897<int:user_id>654/',views.massegeFromManagerInTeacher, name='massegeFromManagerInTeacher'),

    #get massege from teacher and mangager in student
    path('massege_InStudent/897<int:user_id>654/',views.massege_InStudent,name = 'massege_InStudent'),


    #send home work to student from teacher
    path('homework_Teacher/897<int:user_id>654/',views.homework_Teacher,name='homework_Teacher'),
    path('submit_homeworkTeacher/897<int:user_id>654/' ,views.submit_homeworkTeacher,name = 'submit_homeworkTeacher'),

    #get home work from teacher in student
    path('homework_Student/897<int:user_id>654/',views.homework_Student,name = 'homework_Student'),

    #change the massege from the manager in teacher to read
    path('changeToRead_Teacher/897<int:user_id>654/',views.changeToRead_Teacher,name = 'changeToRead_Teacher'),
    
    #change the homework from teacher in student to read
    path('changeToRead_Student_Homework/897<int:user_id>654/',views.changeToRead_Student_Homework, name = 'changeToRead_Student_Homework'),
    
    #change the massege from teacher and manager in student to read
    path('changeToRead_Student_Massege/897<int:user_id>654/',views.changeToRead_Student_Massege, name = "changeToRead_Student_Massege"),

    #add student in teacher 
    path('addStudent/<int:user_id>/',views.addStudent, name = 'addStudent'),
    path('submitAddStudent/<int:user_id>/',views.submitAddStudent, name = 'submitAddStudent'),

    #add teacher in manager
    path('addTeacher/<int:user_id>/',views.addTeacher, name = 'addTeacher'),
    path('submitAddTeacher/<int:user_id>/',views.submitAddTeacher, name = 'submitAddTeacher'),

    #quiz to student in manager
    path('quizManager/<int:user_id>/',views.quizManager, name = 'quizManager'),
    path('submitQuiz/<int:user_id>/',views.submitQuiz, name = 'submitQuiz' ),

    #quiz from manager in student
    path('quizStudent/897<int:user_id>654/',views.quizStudent, name = 'quizStudent'),
    path('answerQuiz/897<int:user_id>654/',views.answerQuiz, name = 'answerQuiz'),


    path('mark_attendance/<int:user_id>/',views.mark_attendance, name='mark_attendance'),

    #guide of the site in studnet
    path('guideToStudent/897<int:user_id>654/',views.guideToStudent,name ='guideToStudent'),


]
urlpatterns += staticfiles_urlpatterns()

users/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from .models import Manager,Teacher,Student,Attendance



class_attendance = (
    ('Present','נוכח'),
    ('Absent','לא נוכח'),
)

class AttendanceForm(forms.Form):
    mark_attendance = forms.ChoiceField(widget=forms.RadioSelect, choices=class_attendance)

users/views.py
from typing import List
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import manager
from django.db.models.fields import NullBooleanField
from django.db.models.query import QuerySet
from django.forms.formsets import formset_factory
from django.shortcuts import render,redirect,get_object_or_404 
from django.http import HttpResponse ,Http404
from users.models import Manager,Teacher,Student,MassegeT, Attendance,Massege_Student_FromManager,Massege_Student_FromTeacher,Homework,Quiz
from homepage import views
from datetime import datetime,timedelta,date
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import AttendanceForm


# Create your views here.

def get_student_signup(request):
    return render(request,'student/signup.html')

def get_teacher_signup(request):
    return render(request,'teacher/signup.html')    

def get_manager_signup(request):
    return render(request,'manager/signup.html') 

def logout_user(request):
    logout(request)
    return redirect('/')

#register to manager 
def submit_Manager(request):
    user_id = request.POST['user_id']
    try: CheckIfManagerExist(user_id)
    except  Manager.DoesNotExist:
        raise Http404(f'Manager with id {user_id} does not exist')
    name = request.POST['name']
    phone_number = request.POST['phone_number']
    school = request.POST['school']
    password = request.POST['password']
    manager = Manager.objects.get(user_id = user_id) 
    manager.name = name
    manager.password = password
    manager.phone_number = phone_number
    manager.school=school
    manager.save()
    return render(request,'manager/signup_success.html') 

#register to teacher 
def submit_Teacher(request):
    user_id = request.POST['user_id']
    try:
        CheckIfTeacherExist(user_id)
    except  Teacher.DoesNotExist:
        raise Http404(f'Teacher with id {user_id} does not exist')
    name = request.POST['name']
    phone_number = request.POST['phone_number']
    password = request.POST['password']
    my_class = request.POST['my_class']
    manager = Teacher.objects.get(user_id= user_id).manager
    teacher = Teacher.objects.get(user_id = user_id)
    teacher.manager = manager
    teacher.name = name
    teacher.password = password
    teacher.user_id = user_id
    teacher.phone_number = phone_number
    teacher.my_class = my_class
    teacher.save()
    return render(request,'teacher/signup_success.html') 

#register to teacher 
def submit_Student(request):
    user_id = request.POST['user_id']
    try:
        CheckIfStudentExist(user_id)
    except  Student.DoesNotExist:
        raise Http404(f'Student with id {user_id} does not exist')
    name = request.POST['name']
    phone_number = request.POST['phone_number']
    password = request.POST['password']
    manager = Student.objects.get(user_id= user_id).manager
    teacher = Student.objects.get(user_id= user_id).teacher
    student = Student.objects.get(user_id = user_id)
    student.name = name
    student.password = password
    student.user_id = user_id
    student.phone_number = phone_number
    student.teacher=teacher
    student.manager=manager
    student.save()
    return render(request,'student/signup_success.html')     

def get_chooseprofile(request):
    return render(request,'chooseprofile.html')


def CheckIfManagerExist(user_id):
    for i in Manager.objects.all():
        if i.user_id == user_id :
            return True

    return False
            

def CheckIfTeacherExist(user_id):
    for i in Teacher.objects.all():
        if i.user_id == user_id :
            return True
    return False
            

def CheckIfStudentExist(user_id):
    for i in Student.objects.all():
        if i.user_id == user_id :
            return True
    return False

#Checks the username and password of an managerr
def Conect_Man(user_id,password): 
    for i in Manager.objects.all():
        if i.user_id == user_id and i.password == password:
           return True
    return False

#Checks the username and password of an Teacher
def Conect_Tec(user_id,password):  
    for i in Teacher.objects.all():
        if i.user_id == user_id and i.password == password:
           return True
    return False

#Checks the username and password of an Student
def Conect_Stu(user_id,password):  
    for i in Student.objects.all():
        if i.user_id == user_id and i.password == password:
           return True
    return False

#func conect to all the users
def Conect(request):
    user_id = request.POST['user_id']
    password = request.POST['password']

    if Conect_Man(user_id,password):             # Chack all the users
       manager = Manager.objects.get(user_id = user_id)
       teachers = Teacher.objects.filter(manager__user_id = user_id)
       return render(request,'manager/Home.html',{'manager':manager ,'teachers' :teachers})
       
    elif Conect_Stu(user_id,password):
        student = Student.objects.get(user_id = user_id)
        return render(request,'student/Home.html',{'student':student})
        
    elif Conect_Tec(user_id,password):
        teacher = Teacher.objects.get(user_id=user_id)
        return render(request,'teacher/Home.html',{'teacher':teacher})
        
    else:
        return render(request,'ConnectError.html')
    
    
#Phones page for teacher
def Phones(request,user_id): 
    teacher = Teacher.objects.get(user_id=user_id)
    student = Student.objects.filter(teacher__user_id = user_id)
    return render(request,'teacher/Phones.html' ,{'teacher':teacher, 'student':student})

#Phones page for manager
def PhonesTeacher(request,user_id): 
    manager = Manager.objects.get(user_id=user_id)
    teacher = Teacher.objects.filter(manager__user_id = user_id)
    return render(request,'manager/PhonesT.html', {'manager' : manager , 'teacher' : teacher})

#Phones page for Student
def PhonesStudent(request,user_id):
    student = Student.objects.get(user_id = user_id)
    Students = Student.objects.filter(teacher__user_id = student.teacher.user_id) #list of Student with same teacher
    return render(request,'student/PhoneStu.html', {'Students' : Students , 'student' : student }) # send to func list of studnet and the student 


# 3 functions for path on the site
def HomePageBetweenPathTeacher(request,user_id):
    teacher = Teacher.objects.get(user_id = user_id)
    return render(request,'teacher/Home.html', {'teacher' : teacher})

def HomePageBetweenPathManager(request,user_id):
    manager = Manager.objects.get(user_id=user_id)
    teachers = Teacher.objects.filter(manager__user_id = user_id)
    return render(request,'manager/Home.html',{'manager' :manager ,'teachers' : teachers})

def HomePageBetweenPathStudent(request,user_id):
    student = Student.objects.get(user_id=user_id)
    return render(request,'student/Home.html',{'student' :student})

#change the student status by health declaration approval
def ChanageStatusStudent(request,user_id):
    student = Student.objects.get(user_id = user_id)
    if(student.status == True):
        student.status = False
        student.save()
    elif(student.status == False):
        student.status = True
        student.save()
    return render(request,'student/changeDoneS.html',{'student' :student})

def ChanageStatusTeacher(request,user_id):
    teacher = Teacher.objects.get(user_id = user_id)
    if(teacher.status == True):
        teacher.status = False
        teacher.save()
    elif(teacher.status == False):
        teacher.status = True
        teacher.save()
    return render(request,'teacher/DoneT.html',{'teacher' :teacher})

def ChanageStatusManager(request,user_id):
    manager = Manager.objects.get(user_id = user_id)
    if(manager.status == True):
        manager.status = False
        manager.save()
    elif(manager.status == False):
        manager.status = True
        manager.save()
    return render(request,'manager/DoneM.html',{'manager' :manager})




#graph of status student for manager
def graphStudentStatus(request,user_id):
    manager = Manager.objects.get(user_id = user_id)
    teachers = Teacher.objects.filter(manager__user_id = user_id)
    students = Student.objects.filter(manager__user_id = user_id)
    numberStudent = 0
    manager.rad_percent = 0 
    manager.green_percent = 0

    for stu in Student.objects.filter(manager = manager):
        if stu.status == False:
            manager.rad_percent += 1
            manager.save()
        else : 
            manager.green_percent +=1
            manager.save()
            
        numberStudent +=1 


    #11
    #percent of the green and red student in the school
    if numberStudent != 0 :
        manager.rad_percent = (manager.rad_percent / numberStudent * 100)
        manager.rad_percent= round(manager.rad_percent,2) #leave only the 2 decimal places
        manager.green_percent = (manager.green_percent / numberStudent * 100)
        manager.green_percent= round(manager.green_percent,2) #leave only the 2 decimal places
        manager.save()


    for teacher in teachers:
        count_red=0
        count_green=0
        students_in_class = Student.objects.filter(teacher__user_id = teacher.user_id)
        for j in students_in_class:
            if j.status == False:
                count_red = count_red+1
            elif j.status == True:
                count_green=count_green+1

        teacher.count_red = count_red
        teacher.count_green = count_green

    return render(request,'manager/graphStudents.html',{'manager' :manager ,'students' : students ,'teachers' :teachers})


#change all the status of students in class to red
def changeMyClassToRed(request,user_id):
    teacher = Teacher.objects.get(user_id = user_id)
    students = Student.objects.filter(teacher__user_id = user_id)
    for i in students:
        i.status = False
        i.save()
    return render(request,'teacher/DoneT.html',{'teacher' :teacher})


#manager add teachers

users/templates/student/Home.html
<!DOCTYPE html>
<title>דף בית תלמיד</title>
<html>

 <head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href='{% static 'stud.css' %}?{% now "U" %}'>
  <style> </style>
  </head>

 <body>
   <div class="topnav">
     <a class="active" href="/users/HomePageStudent/897{{student.user_id}}654" >דף הבית</a >
     <a href="/users/homework_Student/897{{student.user_id}}654"> שיעורי הבית שלי</a>
     <a class="btn" href="/users/PhoneStu/897{{student.user_id}}654" >דף קשר הכיתה שלי</a>
     <a class="btn" href="/users/StuAdministrativePhones/897{{student.user_id}}654" >דף קשר מנהלתי</a>

     <a href="/users/guideToStudent/897{{student.user_id}}654">מדריך </a>
     <a href="/users/massege_InStudent/897{{student.user_id}}654">מסרים </a>
     <a href="/users/quizStudent/897{{student.user_id}}654">שאלון תלמיד </a>

    </div>
   <center>
     <p>
     <h1>  שלום לתלמיד: {{student.name}}</h1>
     </p>
   </center>

    <a id="id1" href="/users/ChanageStatusStudent/897{{student.user_id}}654/">שנה את הסטטוס שלי</a>
    <div class=ha>
      <center>
         בלחיצה על שינוי סטטוס לירוק אני מתחייב שאני אינני מחויב בבידוד או מאובחן כחולה קורונה כמו כן
   
  
        אין לי או לבני משפחתי המתגוררים עמנו, תסמיני קורונה (חום, שיעול, קושי
        בנשימה או כל תסמין נשימתי אחר).
      </center>
  
    </div>
  
  
    {%if student.status == False%}
    <p class=red> </p>
    {%endif%}
    {%if student.status == True%}
    <p class=green> </p>
    {%endif%}
     
     

    {% if student.read_homework == False %}
    <div class=message>
    {{student.name}} קיבלת שיעורי בית מעודכנים , אנא כנס לתיבת שיעורי הבית 
    </div>
    {% endif %}


    {% if student.read_quiz == False %}
    <div class=message>
    {{student.name}} עלייך לענות על שאלון בריאות מטעם המנהל , אנא כנס לתיבת שאלון תלמיד 
  </div>
    {% endif %}

    {% if student.read_massege == False %}
    <div class=message>
    {{student.name}} קיבלת הודעה , אנא כנס לתיבת המסרים  
  </div>
    {% endif %}

   </div>
   <a id="id3" href="{% url 'users:logout_user' %}" class="nav-link" target="_self">התנתקות</a>
  



  </body>
</html>
  
  
  
  
  












































































   


 

users/templates/student/PhoneStu.html
<!DOCTYPE html>
<html>
  <title>דף קשר לתלמיד</title>
  <head>
    {% load static %} {% load static %} <link rel="stylesheet" type="text/css"
    href='{% static 'stud.css' %}?{% now "U" %}'>
    <style></style>
  </head>

  <body dir="rtl">
    <div class="topnav">
      <a class="btn" href="/users/HomePageStudent/897{{student.user_id}}654"
        >דף הבית</a
      >
      <a class="btn" href="/users/homework_Student/897{{student.user_id}}654">
        שיעורי הבית שלי</a
      >
      <a class="active" href="/users/PhoneStu/897{{student.user_id}}654"
        >דף קשר הכיתה שלי</a
      >
      <a
        class="btn"
        href="/users/StuAdministrativePhones/897{{student.user_id}}654"
        >דף קשר מנהלתי</a
      >

      <a class="btn" href="/users/guideToStudent/897{{student.user_id}}654"
        >מדריך
      </a>
      <a class="btn" href="/users/massege_InStudent/897{{student.user_id}}654"
        >מסרים
      </a>
      <a class="btn" href="/users/quizStudent/897{{student.user_id}}654"
        >שאלון תלמיד
      </a>
    </div>
    <center>
      <div class="beautyy">
        תלמיד יקר ,בעמוד זה ישנם מספרי פלאפון של חבריך לכיתה
      </div>
      <ul>
        <h1>דף קשר הכיתה שלי</h1>

        <table id="tableTecher">
          <tr>
            <th>שם התלמיד</th>
            <th>מספר פלאפון</th>
          </tr>
        </table>
        {% for student in Students %}
        <table id="tableTecher">
          <tr>
            {% if student.name %}
            <td>{{student.name}}</td>
            <td>{{student.phone_number}}</td>
            {% endif %}
          </tr>
        </table>
        {% endfor %}
      </ul>
    </center>
  </body>
</html>

users/templates/student/administrativePhones.html
<!DOCTYPE html>
<html>
  <title>דף קשר מנהלתי לתלמיד</title>
  <head>
    {% load static %} {% load static %} <link rel="stylesheet" type="text/css"
    href='{% static 'stud.css' %}?{% now "U" %}'>
    <style></style>
  </head>

  <body dir="rtl">
    <div class="topnav">
      <a class="btn" href="/users/HomePageStudent/897{{student.user_id}}654"
        >דף הבית</a
      >
      <a class="btn" href="/users/homework_Student/897{{student.user_id}}654">
        שיעורי הבית שלי</a
      >
      <a class="btn" href="/users/PhoneStu/897{{student.user_id}}654"
        >דף קשר הכיתה שלי</a
      >
      <a
        class="active"
        href="/users/StuAdministrativePhones/897{{student.user_id}}654"
        >דף קשר מנהלתי</a
      >

      <a class="btn" href="/users/guideToStudent/897{{student.user_id}}654"
        >מדריך
      </a>
      <a class="btn" href="/users/massege_InStudent/897{{student.user_id}}654"
        >מסרים
      </a>
      <a class="btn" href="#about">שאלון תלמיד </a>
    </div>
    <center>
      <div class="beautyy">
        תלמיד יקר ,בעמוד זה ישנם מספרי פלאפון של הצוות המנהלתי בבית ספרך
      </div>
      <ul>
        <h1>דף קשר צוות בית הספר</h1>

        <table id="tableTecher">
          <tr>
            <th>שם המורה</th>
            <th>מספר פלאפון</th>
          </tr>
        </table>

        <table id="tableTecher">
          <tr>
            <td>המנהל/ת שלי {{manager.name}}</td>
            <td>{{manager.phone_number}}</td>
          </tr>
        </table>

        {% for teacher in teachers %}
        <table id="tableTecher">
          <tr>
            {% if teacher.name %} {% if teacher == my_teacher %}
            <td>{{teacher.name}} (המחנכ/ת שלי)</td>
            <td>{{teacher.phone_number}}</td>
            {% else %}
            <td>{{teacher.name}}</td>
            <td>{{teacher.phone_number}}</td>
            {% endif%} {% endif%}
          </tr>
        </table>
        {% endfor %}
      </ul>
    </center>
  </body>
</html>

users/templates/student/changeDoneS.html
<!DOCTYPE html>
<html>
  <title>שינוי סטטוס בוצע בהצלחה</title>
  <head>
    {% load static %} <link rel="stylesheet" type="text/css" href='{% static
    'stud.css' %}?{% now "U" %}'>
    <style></style>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Raleway"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <style>
      p {
        width: 51%;
        height: 0%;
        margin-top: 4%;
        margin-left: 25%;
        color: black;
        font-size: large;
      }
      .w3-row-padding img {
        margin-bottom: 12px;
      }
      .w3-bar .w3-bar-item {
        padding: 8px 16px;
        float: left;
        width: auto;
        border: none;
        display: block;
        outline: 0;
        background-color: rgb(255, 228, 196);
      }
      .w3-padding-32 {
        padding-top: 32px !important;
        padding-bottom: 32px !important;
        background-color: rgb(255, 255, 255);
      }
    </style>
  </head>
  <body>
    <div class="w3-content" style="max-width: 1500px">
      <header class="w3-panel w3-center w3-opacity" style="padding: 128px 16px">
        <h2>!בוצע בהצלחה</h2>
        <div class="w3-padding-32">
          <div class="w3-bar w3-border">
            <a
              href="/users/HomePageStudent/897{{student.user_id}}654"
              class="w3-bar-item w3-button"
              >חזרה לדף הבית</a
            >
          </div>
        </div>
      </header>
    </div>
  </body>
</html>

users/templates/student/signup.html
<!DOCTYPE html>
<html> 
  <title>הרשמה כתלמיד</title> 
 <head> 
    {% load static %}  <link rel="stylesheet" type="text/css"
     href='{% static 'tech.css' %}?{% now "U" %}'> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <style>
      p{
        background-color:rgb(231,231,231);
        padding-top:0.1rem;
        padding-bottom:0.1rem;
        border-radius: 5px;
        box-shadow: 0 5px 7px #ccc;
        text-align:center;
        letter-spacing: 0.2rem;
        margin: 1rem auto;
        } 
       .container {  
         padding: 50px;  
         background-color: rgb(252, 230, 242);  
        }  
  
      input[type=text], input[type=password], textarea {  
        width: 100%;  
        padding: 15px;  
        margin: 5px 0 22px 0;  
        display: inline-block;  
        border: none;  
        background: #f1f1f1;  
      }  
       input[type=text]:focus, input[type=password]:focus {  
         background-color: rgb(255, 249, 197);  
         outline: none;  
       }  
       div {  
           padding: 10px 0;  
         }  
       hr {  
         border: 1px solid #f1f1f1;  
         margin-bottom: 25px;  
       }  
       .registerbtn {  
         background-color: #2b2b2b;  
         color: white;  
         padding: 16px 20px;  
         margin: 8px 0;  
         border: none;  
         cursor: pointer;  
         width: 100%;  
         opacity: 0.9;  
       }  
      .registerbtn:hover {  
        opacity: 1;  
      }  
 
     </style> 
  </head>  
    <body dir="rtl">  

     <div>  
      <center>  <h1> דף הרשמה לתלמיד בית הספר</h1> </center> 
      <center>   <p><h3>הישאר מעודכן ושמור על עצמך</h3> </p></center> 
     <hr>

       <form action = "{% url 'users:submit_Student' %}" method= "post">
         {% csrf_token %}
         <label><b>תעודת זהות</b></label>
         <input type="text" name="user_id" id = "user_id" placeholder="הכנס תעודת זהות" size="9" required />

         <label><b> שם התלמיד</b> </label>  
         <input type="text" name="name" id = "name" placeholder= "הכנס שם מלא" size="20" required />  
 
         <label><b> מספר פלאפון</b></label>  
         <input type="text" name="phone_number" id = "phone_number" placeholder="מספר פלאפון" size="10" required/>     
          
         <label for="password"> <b>    סיסמה </b> </label>  
         <input type="password" placeholder="הכנס סיסמה" name="password" id ="password" required>  
          
         <button type="submit_Student" >הירשם</button>  	
       </form>  
   </body>  
</html>  