CoronaProject/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from CoronaProject import views

urlpatterns = [
    
    url(r'^', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path(r'users/',include('users.urls')),
    path('homepage/',include('homepage.urls')),

]

homepage/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(r'', views.get_homePage, name='home'), # ----/homepage/
    

]

users/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'users'

urlpatterns = [
    url(r'^logout/$', views.logout_user, name='logout_user'),
    path('chooseprofile',views.get_chooseprofile, name = 'chooseprofile'),

    #move to register page 
    path('student/signup',views.get_student_signup, name = 'student_signup'),
    path('teacher/signup',views.get_teacher_signup,name = 'teacher_signup'),
    path(r'manager/signup',views.get_manager_signup, name = 'manager_signup'),

    #register for manager,teacher and student
    path(r'manager/signup_success',views.submit_Manager, name = 'submit_Manager'),
    path(r'teacher/signup_success',views.submit_Teacher, name = 'submit_Teacher'),
    path(r'student/signup_success',views.submit_Student, name = 'submit_Student'),
    
    #connect to all the users
    path(r'Home',views.Conect,name = 'Conect'),

    #phone pages in manager teacher and student
    path('Phones/897<int:user_id>654/',views.Phones),
    path('PhonesT/897<int:user_id>654',views.PhonesTeacher,name = 'PhonesT'),
    path('PhoneStu/897<int:user_id>654',views.PhonesStudent, name = 'PhoneStu'),
    path('StuAdministrativePhones/897<int:user_id>654',views.StuAdministrativePhones, name = 'StuAdministrativePhones'),


    #Home page between paths on the site
    path(r'HomePageTeacher/897<int:user_id>654/',views.HomePageBetweenPathTeacher,name = 'HomePageTeacher'),
    path(r'HomePageManager/897<int:user_id>654/',views.HomePageBetweenPathManager,name = 'HomePageManager'),
    path(r'HomePageStudent/897<int:user_id>654/',views.HomePageBetweenPathStudent, name = 'HomePageStudent'),

    #change status in all the users
    path('ChanageStatusStudent/897<int:user_id>654/',views.ChanageStatusStudent , name = 'ChanageStatusStudent'),
    path('ChanageStatusTeacher/897<int:user_id>654/',views.ChanageStatusTeacher , name = 'ChanageStatusTeacher'),
    path('ChanageStatusManager/897<int:user_id>654/',views.ChanageStatusManager , name = 'ChanageStatusManager'),

    #graph of student status in manager
    path('graphStudentStatus/897<int:user_id>654/',views.graphStudentStatus, name = 'graphStudentStatus'),

    #change all the status of students in class to red
    path('changeMyClassToRed/897<int:user_id>654/',views.changeMyClassToRed,name = 'changeMyClassToRed'),

    #send massege to teacher from manager
    path('massegeForTeacher/897<int:user_id>654/',views.massegeForTeacher, name ='massegeForTeacher'), 
    path('submitMassegeForTeacher/897<int:user_id>654/',views.submitMassegeForTeacher,name = 'submitMassegeForTeacher'),
    
    #send massege to student from manager
    path('massegeForStudentManager/897<int:user_id>654/',views.massegeForStudent_Manager,name = 'massegeForStudentManager' ),
    path('submitMassegeForStudent_Manager/897<int:user_id>654/',views.submitMassegeForStudent_Manager , name = 'submitMassegeForStudent_Manager' ),

    #send massege to class from teacher
    path('massegeForStudentTeacher/897<int:user_id>654/',views.massegeForStudent_Teacher,name='massegeForStudentTeacher'),
    path('submitMassegeForStudent_Teacher/897<int:user_id>654/',views.submitMassegeForStudent_Teacher,name= 'submitMassegeForStudent_Teacher'),

    #get massege from manager in teacher
    path('massegesFromManagerInTeacher/897<int:user_id>654/',views.massegeFromManagerInTeacher, name='massegeFromManagerInTeacher'),

    #get massege from teacher and mangager in student
    path('massege_InStudent/897<int:user_id>654/',views.massege_InStudent,name = 'massege_InStudent'),


    #send home work to student from teacher
    path('homework_Teacher/897<int:user_id>654/',views.homework_Teacher,name='homework_Teacher'),
    path('submit_homeworkTeacher/897<int:user_id>654/' ,views.submit_homeworkTeacher,name = 'submit_homeworkTeacher'),

    #get home work from teacher in student
    path('homework_Student/897<int:user_id>654/',views.homework_Student,name = 'homework_Student'),

    #change the massege from the manager in teacher to read
    path('changeToRead_Teacher/897<int:user_id>654/',views.changeToRead_Teacher,name = 'changeToRead_Teacher'),
    
    #change the homework from teacher in student to read
    path('changeToRead_Student_Homework/897<int:user_id>654/',views.changeToRead_Student_Homework, name = 'changeToRead_Student_Homework'),
    
    #change the massege from teacher and manager in student to read
    path('changeToRead_Student_Massege/897<int:user_id>654/',views.changeToRead_Student_Massege, name = "changeToRead_Student_Massege"),

    #add student in teacher 
    path('addStudent/<int:user_id>/',views.addStudent, name = 'addStudent'),
    path('submitAddStudent/<int:user_id>/',views.submitAddStudent, name = 'submitAddStudent'),

    #add teacher in manager
    path('addTeacher/<int:user_id>/',views.addTeacher, name = 'addTeacher'),
    path('submitAddTeacher/<int:user_id>/',views.submitAddTeacher, name = 'submitAddTeacher'),

    #quiz to student in manager
    path('quizManager/<int:user_id>/',views.quizManager, name = 'quizManager'),
    path('submitQuiz/<int:user_id>/',views.submitQuiz, name = 'submitQuiz' ),

    #quiz from manager in student
    path('quizStudent/897<int:user_id>654/',views.quizStudent, name = 'quizStudent'),
    path('answerQuiz/897<int:user_id>654/',views.answerQuiz, name = 'answerQuiz'),


    path('mark_attendance/<int:user_id>/',views.mark_attendance, name='mark_attendance'),

    #guide of the site in studnet
    path('guideToStudent/897<int:user_id>654/',views.guideToStudent,name ='guideToStudent'),


]
urlpatterns += staticfiles_urlpatterns()

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def get_homePage(request):
    return render(request,'index.html') #use html file
    

homepage/templates/index.html
<!DOCTYPE html>
<html>
  <title>כניסת משתמש</title>
  <head>
  
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    

    
     <style>
      a{
        padding-top:0.1rem;
            padding-bottom:0.1rem;
            border: 2px solid;
            border-color: #333333;
            width: 15%;
            font-size: 25px;
            color: #333333;

            text-align: center;
            margin: 35px;
            width: 14%;
            text-decoration: none;
            padding-right: 2%;
            padding-left: 2%;
            padding-top: 3px;
            display: block;


            box-shadow: 0 5px 7px #ccc;
            text-align:center;
            letter-spacing: 0.2rem;
            border-radius: 1px 1px 1px 1px;
            box-shadow:  1px 1px 1px 1px #ccc;
      }
      
      input[type="id"],
      input[type="password"] {
        width: 66%;
        padding: 9px 10px;
        margin: 26px 84px;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
      }
      input[type="id"]:focus,
      input[type="password"]:focus {
        outline: none;
      }
      .formEntryy {
        display: block;
        margin: 30px auto;
        min-width: 300px;
        padding: 10px;
        border-radius: 2px;
        border: none;
        transition: all 0.5s ease 0s;
     }

      button {
        background-color: #303030;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 22%;
        position: right;
      }

      button:hover {
        opacity: 0.8;
      }
      .title1 {
        background-color: plum;
        color: purple;
        font-size: 315%;
        margin: 17px;
        width: 47%;
        height: 0%;
        font-family: sans-serif;
        margin-left: 1%;
}
body {
  background-color: #f0d7ec;
}

#title-Tag-Line {
  font-size: 20px;
}
 .card-item__bg{
  width: 150px;
  margin-left: auto;
  margin-right: auto;
  left: 0;
  right: 0;
  display: block;
  position: relative;
  margin: 30px auto;
  transform: translate(0px, 50px);
  z-index: 5;
} 

/* form animation starts */
.form {
  background: #fff;
  box-shadow: 0 30px 60px 0 rgba(90, 116, 148, 0.4);
  border-radius: 5px;
  max-width: 480px;
  margin-left: auto;
  margin-right: auto;
  padding-top: 5px;
  padding-bottom: 5px;
  left: 0;
  right: 0;
  position: absolute;
  border-top: 5px solid #c97ab1;

  animation: bounce 1.5s infinite;
}
::-webkit-input-placeholder {
  font-size: 1.3em;
}

.title{
  display: block;
  font-family: sans-serif;
  margin: 10px auto 5px;
  width: 300px;
}
.termsConditions{
  margin: 0 auto 5px 80px;
}

.pageTitle {
    font-size: 2em;
    font-weight: bold;
    text-align: center;
}
.secondaryTitle{
  color: grey;
}

.name {
  background-color: #ebebeb;
  color: rgb(0, 0, 0);
}
.name:hover {
  border-bottom: 5px solid #c97ab1;
  height: 30px;
  width: 380px;
  transition: ease 0.5s;
}

.email {
  background-color: #ebebeb;
  height: 3em;
}

.email:hover {
  border-bottom: 5px solid #c97ab1;
  height: 30px;
  width: 380px;
  transition: ease 0.5s;
}

.message {
  background-color: #ebebeb;
  overflow: hidden;
  height: 10rem;
}

.message:hover {
  border-bottom: 5px solid #c97ab1;
  height: 12em;
  width: 380px;
  transition: ease 0.5s;
}

.formEntry {
  display: block;
  margin: 30px auto;
  min-width: 300px;
  padding: 10px;
  border-radius: 2px;
  border: none;
  transition: all 0.5s ease 0s;
}

.submit {
  width: 200px;
  color: white;
  background-color: #c97ab1;
  font-size: 20px;
}

.submit:hover {
  box-shadow: 15px 15px 15px 5px rgba(78, 72, 77, 0.219);
  transform: translateY(-3px);
  width: 300px;
  border-top: 5px solid #c97ab1;
  border-radius: 0%;
}

@keyframes bounce {
  0% {
    tranform: translate(0, 4px);
  }
  50% {
    transform: translate(0, 8px);
  }
} 

.title2 {
    background-color: #f8d3f8;
    color: #333333;
    font-size: 69%;
    margin: 19px;
    width: 100%;
    height: 2%;
    font-family: sans-serif;
    margin-left: 0%;
}
      .registerbtn {
        width: auto;
        padding: 10px 18px;
        background-color: #e2dcc2;
      }

      .imgcontainer {
        text-align: center;
        margin: 24px 0 12px 0;
      }

      img.avatar {
        width: 40%;
        border-radius: 80%;
      }

      .container {
        padding: 16px;
      }

      /* Change styles for span and cancel button on extra small screens */
      @media screen and (max-width: 300px) {
        span.psw {
          display: block;
          float: none;
        }
        .registerbtn {
          width: 100%;
        }
      }
    </style>
  </head>


  <body dir="rtl">
    
      <form class="form" action = " {% url 'users:Conect' %} " method = "post">

        {% csrf_token %}
        <div class="wrapper">
          
            <div class="pageTitle title">Corona-School </div>
            <center>
              <p id = title1><h3>הישאר מעודכן ושמור על עצמך</h3> </p>
            </center>

        <input type="text" class="name formEntry" placeholder="הכנס תעודת זהות" name="user_id" required />

        
        <input type="password" class="email formEntryy" placeholder="הכנס סיסמה" name="password" required />

        <button class="submit formEntry">התחבר</button>
       

      <a href="users/chooseprofile" id="id2" target="_self">הירשם</a>
      </form>
  

  </body>
</html>

homepage/templates/tt.html
<!DOCTYPE html>
<html>
    <title>בחירת משתמש</title>
    <head>
        <style type= "text/css">
            body{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            }
        p{
            background-color:rgb(231,231,231);
            padding-top:0.1rem;
            padding-bottom:0.1rem;
            border-radius: 5px;
            box-shadow: 0 5px 7px #ccc;
            text-align:center;
            letter-spacing: 0.2rem;
            margin: 1rem auto;


        }
        a{
            padding-top:0.1rem;
            padding-bottom:0.1rem;
            border: 2px solid;
            border-color: #333333;
            width: 15%;
            font-size: 25px;
            color: #333333;

            text-align: center;
            margin: 35px;
            width: 10%;
            text-decoration: none;
            padding-right: 5%;
            padding-left: 5%;
            padding-top: 5px;
            display: block;


            box-shadow: 0 5px 7px #ccc;
            text-align:center;
            letter-spacing: 0.2rem;
            border-radius: 5px 5px 5px 5px;
            box-shadow:  5px 5px 5px 5px #ccc;
        }
        
    </style>
    </head>
    <body>
        <center>
        <p><h2>הישאר מעודכן ושמור על עצמך</h2> </p>
        
        <p id="id2">אנא בחר את המשתמש שלך</p>

        <a href="manager/signup" id="id1" target="_self">מנהל</a>
        <br/>
        <a href="teacher/signup" id="id1" target="_self">מורה</a>
        <br/>
        <a href="student/signup" id="id1" target="_self">תלמיד</a>
        <br/>
    </center>
    </body>
</html>